version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - revive
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - errcheck
