package gui

import "testing"

func TestContextMenuReturnsView(t *testing.T) {
	w := &Window{}
	v := ContextMenu(w, ContextMenuCfg{
		ID:    "cm1",
		Items: []MenuItemCfg{{ID: "a", Text: "A"}},
	})
	if v == nil {
		t.Fatal("expected non-nil view")
	}
}

func TestContextMenuClosedByDefault(t *testing.T) {
	w := &Window{}
	v := ContextMenu(w, ContextMenuCfg{
		ID:    "cm2",
		Items: []MenuItemCfg{{ID: "a", Text: "A"}},
		Content: []View{
			Text(TextCfg{Text: "hello"}),
		},
	})
	layout := v.GenerateLayout(w)
	for _, child := range layout.Children {
		if child.Shape != nil && child.Shape.Float {
			t.Error("no floating child expected when closed")
		}
	}
}

func TestContextMenuOpensOnRightClick(t *testing.T) {
	w := &Window{}
	cfg := ContextMenuCfg{
		ID:    "cm3",
		Items: []MenuItemCfg{{ID: "a", Text: "A"}},
	}
	idFocus := fnvSum32("context_menu_" + cfg.ID)

	v := ContextMenu(w, cfg)
	layout := v.GenerateLayout(w)

	if layout.Shape.Events == nil {
		t.Fatal("expected events")
	}

	e := &Event{MouseButton: MouseRight, MouseX: 10, MouseY: 20}
	layout.Shape.Events.OnClick(&layout, e, w)

	if !e.IsHandled {
		t.Error("expected IsHandled")
	}
	st := StateReadOr[string, contextMenuState](
		w, nsContextMenu, "cm3", contextMenuState{})
	if !st.Open {
		t.Error("expected open")
	}
	if !w.IsFocus(idFocus) {
		t.Error("expected focus set")
	}
}

func TestContextMenuClosesOnLeftClick(t *testing.T) {
	w := &Window{}
	sm := StateMap[string, contextMenuState](w, nsContextMenu, capFew)
	sm.Set("cm4", contextMenuState{Open: true, X: 5, Y: 5})

	v := ContextMenu(w, ContextMenuCfg{
		ID:    "cm4",
		Items: []MenuItemCfg{{ID: "a", Text: "A"}},
	})
	layout := v.GenerateLayout(w)

	e := &Event{MouseButton: MouseLeft}
	layout.Shape.Events.OnClick(&layout, e, w)

	st := StateReadOr[string, contextMenuState](
		w, nsContextMenu, "cm4", contextMenuState{})
	if st.Open {
		t.Error("expected closed after left click")
	}
}

func TestContextMenuClosesOnFocusLoss(t *testing.T) {
	w := &Window{}
	sm := StateMap[string, contextMenuState](w, nsContextMenu, capFew)
	sm.Set("cm5", contextMenuState{Open: true, X: 5, Y: 5})

	cfg := ContextMenuCfg{
		ID:    "cm5",
		Items: []MenuItemCfg{{ID: "a", Text: "A"}},
	}
	idFocus := fnvSum32("context_menu_" + cfg.ID)
	w.SetIDFocus(idFocus)

	v := ContextMenu(w, cfg)
	layout := v.GenerateLayout(w)

	// Lose focus.
	w.SetIDFocus(0)
	layout.Shape.Events.AmendLayout(nil, w)

	st := StateReadOr[string, contextMenuState](
		w, nsContextMenu, "cm5", contextMenuState{})
	if st.Open {
		t.Error("expected closed on focus loss")
	}
}

func TestContextMenuActionFires(t *testing.T) {
	w := &Window{}
	sm := StateMap[string, contextMenuState](w, nsContextMenu, capFew)
	sm.Set("cm6", contextMenuState{Open: true, X: 0, Y: 0})

	var firedID string
	cfg := ContextMenuCfg{
		ID:    "cm6",
		Items: []MenuItemCfg{{ID: "cut", Text: "Cut"}},
		Action: func(id string, _ *Event, _ *Window) {
			firedID = id
		},
	}
	w.SetIDFocus(fnvSum32("context_menu_" + cfg.ID))

	// Build the popup action wrapper directly.
	action := func(id string, e *Event, w *Window) {
		sm := StateMap[string, contextMenuState](
			w, nsContextMenu, capFew)
		sm.Set(cfg.ID, contextMenuState{})
		if cfg.Action != nil {
			cfg.Action(id, e, w)
		}
	}

	e := &Event{MouseButton: MouseLeft}
	action("cut", e, w)

	if firedID != "cut" {
		t.Errorf("expected 'cut', got %q", firedID)
	}
}

func TestContextMenuActionClosesMenu(t *testing.T) {
	w := &Window{}
	sm := StateMap[string, contextMenuState](w, nsContextMenu, capFew)
	sm.Set("cm7", contextMenuState{Open: true, X: 0, Y: 0})

	cfg := ContextMenuCfg{
		ID:    "cm7",
		Items: []MenuItemCfg{{ID: "a", Text: "A"}},
	}

	// Simulate the wrapped action.
	action := func(id string, e *Event, w *Window) {
		sm := StateMap[string, contextMenuState](
			w, nsContextMenu, capFew)
		sm.Set(cfg.ID, contextMenuState{})
	}

	e := &Event{MouseButton: MouseLeft}
	action("a", e, w)

	st := StateReadOr[string, contextMenuState](
		w, nsContextMenu, "cm7", contextMenuState{})
	if st.Open {
		t.Error("expected closed after action")
	}
}

func TestContextMenuIDFocusAutoGenerated(t *testing.T) {
	w := &Window{}
	v := ContextMenu(w, ContextMenuCfg{
		ID:    "cm8",
		Items: []MenuItemCfg{{ID: "a", Text: "A"}},
	})
	layout := v.GenerateLayout(w)

	expected := fnvSum32("context_menu_cm8")
	if layout.Shape.IDFocus != expected {
		t.Errorf("expected IDFocus=%d, got %d",
			expected, layout.Shape.IDFocus)
	}
}

func TestContextMenuDefaults(t *testing.T) {
	cfg := ContextMenuCfg{ID: "cm9"}
	applyContextMenuDefaults(&cfg)

	d := &DefaultMenubarStyle
	if cfg.Color != d.Color {
		t.Error("Color not defaulted")
	}
	if cfg.ColorBorder != d.ColorBorder {
		t.Error("ColorBorder not defaulted")
	}
	if cfg.ColorSelect != d.ColorSelect {
		t.Error("ColorSelect not defaulted")
	}
	if cfg.TextStyle != d.TextStyle {
		t.Error("TextStyle not defaulted")
	}
	if cfg.PaddingMenuItem != d.PaddingMenuItem {
		t.Error("PaddingMenuItem not defaulted")
	}
	if cfg.PaddingSubmenu != d.PaddingSubmenu {
		t.Error("PaddingSubmenu not defaulted")
	}
}

func TestContextMenuUserOnAnyClickForwarded(t *testing.T) {
	w := &Window{}
	fired := false
	v := ContextMenu(w, ContextMenuCfg{
		ID:    "cm10",
		Items: []MenuItemCfg{{ID: "a", Text: "A"}},
		OnAnyClick: func(_ *Layout, _ *Event, _ *Window) {
			fired = true
		},
	})
	layout := v.GenerateLayout(w)

	e := &Event{MouseButton: MouseRight}
	layout.Shape.Events.OnClick(&layout, e, w)

	if !fired {
		t.Error("user OnAnyClick not forwarded")
	}
}

func TestContextMenuUserOnAnyClickHandled(t *testing.T) {
	w := &Window{}
	v := ContextMenu(w, ContextMenuCfg{
		ID:    "cm11",
		Items: []MenuItemCfg{{ID: "a", Text: "A"}},
		OnAnyClick: func(_ *Layout, e *Event, _ *Window) {
			e.IsHandled = true
		},
	})
	layout := v.GenerateLayout(w)

	e := &Event{MouseButton: MouseRight}
	layout.Shape.Events.OnClick(&layout, e, w)

	// Menu should NOT have opened since user handler set IsHandled.
	st := StateReadOr[string, contextMenuState](
		w, nsContextMenu, "cm11", contextMenuState{})
	if st.Open {
		t.Error("menu should not open when user handler sets IsHandled")
	}
}
